# Generated by Django 4.2.6 on 2023-10-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
