# Generated by Django 4.2.6 on 2023-10-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_alter_karyawan_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
