# Generated by Django 4.2.6 on 2023-10-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0004_alter_karyawan_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
